SELECT C.CAR_ID,
       C.CAR_TYPE,
       ROUND(C.DAILY_FEE * P.RATE * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
) H ON C.CAR_ID = H.CAR_ID
INNER JOIN (
    SELECT CAR_TYPE,
           (100 - DISCOUNT_RATE) / 100 AS RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
) P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND H.CAR_ID IS NULL
AND ROUND(C.DAILY_FEE * P.RATE * 30) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
